export default {
  TESTS: "/tests",
  DELETED_TESTS: "/tests/deleted",
  TEST_ID: "/test/:id",
  EDIT_TEST_ID: "/test/edit/:id",
  RESTORE_TEST_ID: "/test/restore/:id",
  FORCE_DELETE_TEST_ID: "/test/forceDelete/:id",
  TESTS_CHILD: "/testsChild",
  DELETED_TESTS_CHILD: "/testsChild/deleted",
  TEST_CHILD_ID: "/testChild/:id",
  EDIT_TEST_CHILD_ID: "/testChild/edit/:id",
  RESTORE_TEST_CHILD_ID: "/testChild/restore/:id",
  FORCE_DELETE_TEST_CHILD_ID: "/testChild/forceDelete/:id",
  USERS: "/users",
  DELETED_USERS: "/users/deleted",
  USER_ID: "/user/:id",
  EDIT_USER_ID: "/user/edit/:id",
  RESTORE_USER_ID: "/user/restore/:id",
  FORCE_DELETE_USER_ID: "/user/forceDelete/:id",
};
