export const RESOURCE = {
  AUTH: "Auth",
  DEV: "dev",
  PRODUCTION: "production",
  DEVELOPMENT: "development",
  API: "/api/",
  V1: "v1/",
  VALIDATION_ERROR: "ValidationError",
  NOT_FOUND: "Not Found",
  CLOUDINARY_FOLDER: "projectImages",
  FINISH: "finish",
  PRE_HANDLER: "preHandler",
  ID: "_id",
  ROLE: "role",
  PASSWORD: "+password",
  GMAIL: "gmail",
  TESTS: "tests",
  TEST: "test",
  TESTS_CHILD: "testsChild",
  USERS: "users",
};
