export const RESOURCE = {
  AUTH: "Auth",
  PRODUCTION: "production",
  DEVELOPMENT: "development",
  INTERNAL_SERVER_ERROR: "Internal server error",
  API: "api",
  V1: "/v1",
  IMAGES: "projectImages",
  ID: "id",
  _ID: "_id",
  ROLE: "role",
  ROLES: "roles",
  PASSWORD: "+password",
  TESTS: "tests",
  TEST: "test",
  TESTS_CHILD: "testsChild",
  USERS: "users",
};
