export function filterBadWords(value: string): boolean {
  const badWords = [
    "anal",
    "anus",
    "arse",
    "ass",
    "ballsack",
    "balls",
    "bastard",
    "bitch",
    "biatch",
    "bloody",
    "blowjob",
    "bollock",
    "bollok",
    "boner",
    "boob",
    "bugger",
    "bum",
    "butt",
    "buttplug",
    "clitoris",
    "cock",
    "coon",
    "crap",
    "cunt",
    "damn",
    "dick",
    "dildo",
    "dyke",
    "fag",
    "feck",
    "fellate",
    "fellatio",
    "felching",
    "fuck",
    "fudgepacker",
    "flange",
    "goddamn",
    "hell",
    "homo",
    "jizz",
    "knobend",
    "labia",
    "muff",
    "nigger",
    "nigga",
    "penis",
    "piss",
    "poop",
    "prick",
    "pube",
    "pussy",
    "queer",
    "scrotum",
    "sex",
    "shit",
    "sh1t",
    "slut",
    "smegma",
    "spunk",
    "suck",
    "tit",
    "tosser",
    "turd",
    "twat",
    "vagina",
    "wank",
    "whore",
    "wtf",
    "screw",
    "fck",
    "fcc",
    "sht",
    "gago",
    "tang ina mo",
    "putang ina mo",
    "tanga",
    "bobo",
    "vovo",
    "bovo",
    "tukmol",
    "ulopong",
    "tarantado",
    "sira ulo",
    "siraulo",
    "lintek",
    "kantot",
    "kantut",
    "kantutan",
    "kantotan",
    "sucker",
    "king ina mo",
    "pota",
    "puta",
    "gagi",
    "bwakang ina mo",
    "tite",
    "betlog",
    "pwet",
    "dede",
    "pepe",
    "puke",
    "pekpek",
    "titi",
    "bulbul",
    "burat",
    "tamod",
    "inutil",
    "utak talangka",
    "puday",
    "walang kwenta",
    "basura",
    "bulok",
    "bubu",
    "potang ina mo",
    "bopols",
    "unggoy",
    "ukininam",
    "baninam",
    "buwisit",
    "leche",
    "pakshet",
    "pucha",
    "ulol",
    "olol",
    "obob",
    "lintik",
    "punyeta",
    "tarantadu",
    "tang ina",
    "baho",
    "lowlife",
    "gagu",
    "moron",
    "bubo",
    "pulpol",
    "polpol",
    "bantot",
    "pukinang ina mo",
  ];

  const regex = new RegExp(badWords.join("|"), "gi");
  return !regex.test(value);
}
